{
    "name": """Multi-Brand Backend""",
    "summary": """Technical module to switch Websites in Backend similarly to Company Switcher""",
    "category": "Hidden",
    # "live_test_url": "",
    "images": [],
    "version": "13.0.4.0.2",
    "application": False,
    "author": "Roaya",
    "website": "https://www.roayadm.com",
    "depends": ["web", "website", "base_setup"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "views/res_users_views.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/ir_property_views.xml",
        "views/assets.xml",
    ],
    "demo": ["demo/assets_demo.xml", "demo/res_users_demo.xml"],
    "qweb": ["static/src/xml/qweb.xml"],
    "post_load": "post_load",
    "pre_init_hook": None,
    "post_init_hook": "post_init_hook",
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
